--- 
abstract: "Perl extension for L-BFGS "
author: 
  - Laye Suen, <laye@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Algorithm-LBFGS
no_index: 
  directory: 
    - inc
    - t
version: 0.16
